added wrap errors #23
sah4ez/now pull request #47
Opened 2020-01-27 02:06 UTC by marti1125

* I just added a some error.Wrap

please check

2020-01-27 07:36 UTC, sah4ez commented
O! Cool! Thank you! You can continue with other commands. And be careful with cause of return error.

2020-02-15 04:23 UTC, marti1125 commented
hi @sah4ez I just added more errors.Wrap

2020-02-16 14:10 UTC, sah4ez requested changes
Need fix text of some errors and we can merge it.

2020-02-16 14:10 UTC, sah4ez commented on cmd/cli/group.go
> +						return errors.Wrap(err, "start-join-group publish")
This FinishGroup method.

2020-02-16 14:10 UTC, sah4ez commented on cmd/cli/encrypt.go
> +				return errors.Wrap(err, "can not read the path")
This error about failed read the key.bin

2020-02-16 14:10 UTC, sah4ez commented on cmd/cli/group.go
> +						return errors.Wrap(err, "start-join-group load")
This FinishGroup method.

2020-02-17 01:14 UTC, marti1125 commented
Hi @sah4ez I updated the error message :+1:

2020-02-17 07:09 UTC, sah4ez approved these changes

2020-02-17 07:10 UTC, sah4ez approved these changes

2020-02-17 07:10 UTC, merged